{% set name = "carma" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RUrlus/carma/archive/v{{ version }}.tar.gz
  sha256: a0b229d33760edc0e5be7c115d21ea9ccd86b77bda8055bc16ac3a2ff6fc01ec

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/include/carma/carma  # [unix]

about:
  home: https://github.com/RUrlus/carma
  summary: A C++ header only library providing conversions between Numpy arrays and Armadillo matrices.
  description: |
    CARMA provides fast bidirectional conversions between Numpy arrays and
    Armadillo matrices, vectors and cubes, much like RcppArmadillo does for R
    and Armadillo.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://carma.readthedocs.io
  dev_url: https://github.com/RUrlus/carma

extra:
  recipe-maintainers:
    - zklaus
    - timkpaine
